{
 "title": "homework_5",
 "description": "testing save",
 "time": { "from": "2024-03-01T00:00:00.000Z", "to": "2024-03-31T22:59:59.000Z" },
 "panels": [
  {
   "title": "Column Quantile Metric",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", column_quantile_metric FROM homework_5 LIMIT 50 "
    }
   ]
  },
  {
   "title": "missing values",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", share_missing_values FROM homework_5 LIMIT 50 "
    }
   ]
  },
  {
   "title": "drifted columns",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", num_drifted_columns FROM homework_5 LIMIT 50 "
    }
   ]
  },
  {
   "title": "prediction drift",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", prediction_drift FROM homework_5 LIMIT 50 "
    }
   ]
  }
 ]
}