version: '3.10'

services:
  localstack:
    image: localstack/localstack
    container_name: localstack
    environment:
      - SERVICES=s3
      - DEBUG=1
      - AWS_ACCESS_KEY_ID=abc
      - AWS_SECRET_ACCESS_KEY=xyz
    ports:
      - "4566:4566"
      - "4571:4571"
    volumes:
      - "./localstack:/localstack_tmp"
